[workspace]
resolver = "2"
members = [
    "deck_gen",
    "prepare_pdf_host",
    "prepare_pdf_web",
    "deck_gen_wasm",
    "deck_gen_wasm/modules/conf",
    "deck_gen_wasm/modules/fs",
    "deck_gen_wasm/modules/browser",
    "deck_gen_wasm/modules/persist",
    "deck_gen_wasm/modules/export",
    "deck_gen_wasm/modules/import",
    "deck_gen_wasm/modules/template",
    "deck_gen_wasm/modules/workspace",
    "progress_viewer",
    "deck_gen_wasm/modules/feedback",
    "deck_gen_wasm/modules/locale",
    "deck_gen_wasm/modules/ui",
]
default-members = ["deck_gen", "prepare_pdf_host"]

[workspace.package]
edition = "2021"
version = "0.1.0"
