[workspace]
resolver = "2"
members = [
    "deck_gen",
    "prepare_pdf_host",
    "prepare_pdf_web",
    "deck_gen_wasm",
    "deck_gen_wasm/conf",
    "deck_gen_wasm/fs",
    "deck_gen_wasm/browser",
    "deck_gen_wasm/persist",
    "deck_gen_wasm/export",
    "deck_gen_wasm/import",
    "deck_gen_wasm/template",
    "deck_gen_wasm/workspace",
    "deck_gen_wasm/progress",
    "deck_gen_wasm/feedback",
    "deck_gen_wasm/locale",
    "deck_gen_wasm/ui",
]
default-members = ["deck_gen", "prepare_pdf_host"]

[workspace.package]
edition = "2021"
version = "0.1.0"
