//! AI agent for the browser workspace: one prompt → tool loop on a VFS.
//!
//! Isolated from Leptos / UI. Public surface is [`AiEngine`] (`from_conf`,
//! `run_loop`) plus helpers to install bundled model files and list configs.

mod conf;
mod engine;
mod gemini;
mod http;
mod install;
mod log;
mod openai;
mod tools;

#[cfg(test)]
mod live;

pub use crate::conf::{list_model_files, parse_model_conf, ModelConf, ModelFile, ModelKind};
pub use crate::engine::{AiEngine, AiRequest};
pub use crate::install::{install_ai_defaults, needs_ai_install};
pub use crate::log::log_file_name;
pub use crate::tools::is_autogenerated_path;
