//! Agent tools over `&mut Vfs`. Writes under `_autogenerated/` are refused
//! except [`deck_gen::prepare_html`], which is allowed to create autogen files.

use std::sync::Arc;

use deck_gen_wasm_fs::{Vfs, VfsFs};
use serde_json::{json, Value};

/// True when `path` is `_autogenerated` or lives under such a folder (any game).
pub fn is_autogenerated_path(path: &str) -> bool {
    path.split('/').any(|seg| seg == "_autogenerated")
}

pub(crate) fn tool_declarations() -> Value {
    json!([
        {
            "name": "ls",
            "description": "List children of a directory. Empty path is the VFS root. Returns name and file/dir for each child.",
            "parameters": {
                "type": "object",
                "properties": {
                    "path": { "type": "string", "description": "Directory path, or empty for root" }
                },
                "required": ["path"]
            }
        },
        {
            "name": "read_file",
            "description": "Read a UTF-8 text file. Errors if missing, a directory, or not UTF-8.",
            "parameters": {
                "type": "object",
                "properties": {
                    "path": { "type": "string" }
                },
                "required": ["path"]
            }
        },
        {
            "name": "write_file",
            "description": "Create or overwrite a UTF-8 text file. Parent folders are created. Forbidden under _autogenerated/.",
            "parameters": {
                "type": "object",
                "properties": {
                    "path": { "type": "string" },
                    "content": { "type": "string" }
                },
                "required": ["path", "content"]
            }
        },
        {
            "name": "mkdir",
            "description": "Create a directory (and parents). Forbidden under _autogenerated/.",
            "parameters": {
                "type": "object",
                "properties": {
                    "path": { "type": "string" }
                },
                "required": ["path"]
            }
        },
        {
            "name": "remove",
            "description": "Delete a file or a directory tree. Forbidden under _autogenerated/.",
            "parameters": {
                "type": "object",
                "properties": {
                    "path": { "type": "string" }
                },
                "required": ["path"]
            }
        },
        {
            "name": "prepare_html",
            "description": "Run deck_gen prepare_html on the whole VFS. Writes HTML under each game's _autogenerated/. Call this after editing sources and fix any errors it reports. Do not write autogen files yourself.",
            "parameters": {
                "type": "object",
                "properties": {}
            }
        }
    ])
}

pub(crate) fn execute_tool(vfs: &mut Vfs, name: &str, args: &Value) -> String {
    match name {
        "ls" => tool_ls(vfs, args),
        "read_file" => tool_read(vfs, args),
        "write_file" => tool_write(vfs, args),
        "mkdir" => tool_mkdir(vfs, args),
        "remove" => tool_remove(vfs, args),
        "prepare_html" => tool_prepare_html(vfs),
        other => format!("unknown tool: {other}"),
    }
}

fn arg_str<'a>(args: &'a Value, key: &str) -> Result<&'a str, String> {
    args.get(key)
        .and_then(Value::as_str)
        .ok_or_else(|| format!("missing string argument '{key}'"))
}

fn deny_autogen_write(path: &str) -> Result<(), String> {
    if is_autogenerated_path(path) {
        Err(format!(
            "write access denied under _autogenerated/ ({path}). Use prepare_html instead."
        ))
    } else {
        Ok(())
    }
}

fn tool_ls(vfs: &Vfs, args: &Value) -> String {
    let path = match arg_str(args, "path") {
        Ok(p) => p,
        Err(e) => return e,
    };
    if !vfs.is_dir(path) {
        return format!("'{path}' is not a directory");
    }
    let mut lines = Vec::new();
    for (name, is_dir) in vfs.children(path) {
        let kind = if is_dir { "dir" } else { "file" };
        lines.push(format!("{kind}\t{name}"));
    }
    if lines.is_empty() {
        "(empty)".into()
    } else {
        lines.join("\n")
    }
}

fn tool_read(vfs: &Vfs, args: &Value) -> String {
    let path = match arg_str(args, "path") {
        Ok(p) => p,
        Err(e) => return e,
    };
    if vfs.is_dir(path) {
        return format!("'{path}' is a folder");
    }
    if !vfs.is_file(path) {
        return format!("'{path}' not found");
    }
    match vfs.read_file(path) {
        Some(body) => body.to_string(),
        None => format!("'{path}' is not UTF-8 text"),
    }
}

fn tool_write(vfs: &mut Vfs, args: &Value) -> String {
    let path = match arg_str(args, "path") {
        Ok(p) => p,
        Err(e) => return e,
    };
    let content = match arg_str(args, "content") {
        Ok(p) => p,
        Err(e) => return e,
    };
    if let Err(e) = deny_autogen_write(path) {
        return e;
    }
    match vfs.put_file(path, content.to_string()) {
        Ok(()) => format!("wrote {path} ({} bytes)", content.len()),
        Err(e) => e,
    }
}

fn tool_mkdir(vfs: &mut Vfs, args: &Value) -> String {
    let path = match arg_str(args, "path") {
        Ok(p) => p,
        Err(e) => return e,
    };
    if let Err(e) = deny_autogen_write(path) {
        return e;
    }
    match vfs.mkdir(path) {
        Ok(()) => format!("mkdir {path}"),
        Err(e) => e,
    }
}

fn tool_remove(vfs: &mut Vfs, args: &Value) -> String {
    let path = match arg_str(args, "path") {
        Ok(p) => p,
        Err(e) => return e,
    };
    if let Err(e) = deny_autogen_write(path) {
        return e;
    }
    match vfs.remove(path) {
        Ok(()) => format!("removed {path}"),
        Err(e) => e,
    }
}

fn tool_prepare_html(vfs: &mut Vfs) -> String {
    let fs = Arc::new(VfsFs::new(vfs.clone()));
    let result = deck_gen::prepare_html(fs.clone(), false, &progress_viewer::NoopProgress);
    *vfs = VfsFs::try_unwrap_or_clone(fs);
    match result {
        Ok(n) => format!("prepare_html: prepared {n} decks"),
        Err(err) => format!("prepare_html error: {err}"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn autogen_writes_are_blocked_reads_are_not() {
        let mut vfs = Vfs::default();
        vfs.put_file("games/x/_autogenerated/preview.html", "old".into())
            .unwrap();
        let err = execute_tool(
            &mut vfs,
            "write_file",
            &json!({"path": "games/x/_autogenerated/preview.html", "content": "nope"}),
        );
        assert!(err.contains("_autogenerated"), "{err}");
        assert_eq!(
            vfs.read_file("games/x/_autogenerated/preview.html"),
            Some("old")
        );
        let err = execute_tool(
            &mut vfs,
            "remove",
            &json!({"path": "games/x/_autogenerated/preview.html"}),
        );
        assert!(err.contains("_autogenerated"), "{err}");
        let err = execute_tool(
            &mut vfs,
            "mkdir",
            &json!({"path": "games/x/_autogenerated/extra"}),
        );
        assert!(err.contains("_autogenerated"), "{err}");
        let body = execute_tool(
            &mut vfs,
            "read_file",
            &json!({"path": "games/x/_autogenerated/preview.html"}),
        );
        assert_eq!(body, "old");
    }

    #[test]
    fn prepare_html_may_write_autogen() {
        let mut vfs = Vfs::default();
        let msg = execute_tool(&mut vfs, "prepare_html", &json!({}));
        assert!(
            msg.starts_with("prepare_html"),
            "tool must run, got {msg}"
        );
    }

    #[test]
    fn ls_root_and_write_normal_file() {
        let mut vfs = Vfs::default();
        let msg = execute_tool(
            &mut vfs,
            "write_file",
            &json!({"path": "games/a/note.md", "content": "hi"}),
        );
        assert!(msg.contains("wrote"), "{msg}");
        let listing = execute_tool(&mut vfs, "ls", &json!({"path": "games"}));
        assert!(listing.contains("a"), "{listing}");
    }
}
