//! Runtime layout loaded from the three `conf.json5` files.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::{Arc, OnceLock};

use serde::de::DeserializeOwned;

use crate::error::{Error, Result};
use crate::fs::FileSystem;

mod locate;
mod schema;

pub use schema::{ChromeSettings, OutputNames, PrintSettings};

#[cfg(not(target_arch = "wasm32"))]
pub(crate) use locate::{canonicalize_or_abs, os_search_roots};
use locate::find_conf_file;
use schema::{GameFile, GamesRootFile, RootFile};

const CONF_FILE_NAME: &str = "conf.json5";

static CONF: OnceLock<Arc<Conf>> = OnceLock::new();

#[derive(Debug)]
pub struct Conf {
    pub root: PathBuf,
    pub games_root: PathBuf,
    pub default_game: String,
    pub chrome: ChromeSettings,
    pub games: HashMap<String, GamePaths>,
}

#[derive(Debug, Clone)]
pub struct GamePaths {
    pub id: String,
    pub root: PathBuf,
    pub decks: PathBuf,
    pub views: PathBuf,
    pub vars: PathBuf,
    pub rules: PathBuf,
    pub autogenerated: PathBuf,
    pub duplex: PathBuf,
    pub output: OutputNames,
    pub print: PrintSettings,
}

/// Inject a conf (wasm / tests). Ignored if one is already loaded.
pub fn set_conf(conf: Conf) -> Arc<Conf> {
    CONF.get_or_init(|| Arc::new(conf)).clone()
}

pub fn conf() -> Result<Arc<Conf>> {
    if let Some(existing) = CONF.get() {
        return Ok(existing.clone());
    }
    #[cfg(target_arch = "wasm32")]
    {
        Err(Error::msg(
            "Native conf discovery is not available in wasm; use prepare_html with a FileSystem",
        ))
    }
    #[cfg(not(target_arch = "wasm32"))]
    {
        let loaded = Arc::new(load(&crate::fs::OsFs)?);
        Ok(CONF.get_or_init(|| loaded).clone())
    }
}

pub fn load(fs: &dyn FileSystem) -> Result<Conf> {
    match find_conf_file(fs) {
        Ok(path) => build_conf(fs, path),
        Err(err) => {
            let virtual_root = fs.search_roots().iter().any(|root| root.as_os_str().is_empty());
            if virtual_root || fs.is_dir(Path::new("games")) {
                load_workspace_fallback(fs)
            } else {
                Err(err)
            }
        }
    }
}

impl Conf {
    pub fn game(&self, id: Option<&str>) -> Result<&GamePaths> {
        let key = id.unwrap_or(self.default_game.as_str());
        self.games.get(key).ok_or_else(|| {
            let known = self.games.keys().cloned().collect::<Vec<_>>().join(", ");
            Error::msg(format!("Unknown game {key:?}. Known: {known}"))
        })
    }

    pub fn game_for_deck_name(&self, name: &str) -> Result<&GamePaths> {
        let id = name.split('.').next().unwrap_or("");
        self.game(Some(id))
    }
}

pub fn output_dir_for_name(loaded: &Conf, name: &str) -> Result<PathBuf> {
    let game = loaded.game_for_deck_name(name)?;
    let prefix = format!("{}.", game.id);
    let rest = name.strip_prefix(&prefix).ok_or_else(|| {
        Error::msg(format!("Deck name {name:?} must start with '{}.'", game.id))
    })?;
    let mut path = game.autogenerated.clone();
    for part in rest.split('.').filter(|part| !part.is_empty()) {
        path.push(part);
    }
    Ok(path)
}

pub fn views_for_deck_name(loaded: &Conf, name: &str) -> Result<PathBuf> {
    Ok(loaded.game_for_deck_name(name)?.views.clone())
}

fn load_workspace_fallback(fs: &dyn FileSystem) -> Result<Conf> {
    let games_root = PathBuf::from("games");
    let games = if fs.is_dir(&games_root) {
        discover_games(fs, &games_root)?
    } else {
        HashMap::new()
    };
    let games_conf_path = games_root.join(CONF_FILE_NAME);
    let default_game = if fs.is_file(&games_conf_path) {
        let games_raw: GamesRootFile = parse_json5_file(fs, &games_conf_path)?;
        games_raw.default_game
    } else {
        games.keys().next().cloned().unwrap_or_default()
    };
    Ok(Conf {
        root: PathBuf::new(),
        games_root,
        default_game,
        chrome: ChromeSettings::default(),
        games,
    })
}

fn build_conf(fs: &dyn FileSystem, conf_path: PathBuf) -> Result<Conf> {
    let raw: RootFile = parse_json5_file(fs, &conf_path)?;
    let root = conf_path
        .parent()
        .ok_or_else(|| Error::file(&conf_path, "has no parent directory"))?
        .to_path_buf();
    let games_root = root.join(&raw.games_root);
    let games_conf_path = games_root.join(CONF_FILE_NAME);
    let games_raw: GamesRootFile = parse_json5_file(fs, &games_conf_path)?;
    let games = discover_games(fs, &games_root)?;
    if games.is_empty() {
        return Err(Error::file(
            &games_root,
            "must contain at least one game folder with conf.json5",
        ));
    }
    if !games.contains_key(&games_raw.default_game) {
        return Err(Error::file(
            &games_conf_path,
            format!(
                "default_game {:?} is not a known game-name",
                games_raw.default_game
            ),
        ));
    }
    Ok(Conf {
        root,
        games_root,
        default_game: games_raw.default_game,
        chrome: raw.chrome,
        games,
    })
}

fn discover_games(fs: &dyn FileSystem, games_root: &Path) -> Result<HashMap<String, GamePaths>> {
    if !fs.is_dir(games_root) {
        return Err(Error::file(games_root, "is not a directory"));
    }
    let mut games = HashMap::new();
    for path in fs.read_dir(games_root)? {
        if !fs.is_dir(&path) {
            continue;
        }
        let conf_path = path.join(CONF_FILE_NAME);
        if !fs.is_file(&conf_path) {
            continue;
        }
        let spec: GameFile = parse_json5_file(fs, &conf_path)?;
        let id = spec.game_name.clone();
        if games.contains_key(&id) {
            return Err(Error::file(
                &conf_path,
                format!("duplicate game-name {id:?}"),
            ));
        }
        games.insert(id.clone(), resolve_game(path, id, spec));
    }
    Ok(games)
}

fn resolve_game(game_root: PathBuf, id: String, spec: GameFile) -> GamePaths {
    let folders = spec.folders;
    GamePaths {
        id,
        decks: game_root.join(&folders.decks),
        views: game_root.join(&folders.views),
        vars: game_root.join(&folders.vars),
        rules: game_root.join(&folders.rules),
        autogenerated: game_root.join(&folders.autogenerated),
        duplex: game_root.join(&folders.duplex),
        root: game_root,
        output: spec.output,
        print: spec.print,
    }
}

fn parse_json5_file<T: DeserializeOwned>(fs: &dyn FileSystem, path: &Path) -> Result<T> {
    let text = fs.read_to_string(path)?;
    json5::from_str(&text).map_err(|err| Error::file(path, format!("invalid JSON5: {err}")))
}
