//! Runtime layout loaded from the three `conf.json5` files.
//!
//! There is a repository-root file (games folder + Chrome search), a games-root
//! file (`default_game`), and one file per game (folders, output names, print).
//! [`load`] walks a [`FileSystem`] and resolves every relative folder to a
//! `PathBuf`. The native CLI caches the result in a process-wide cell; WASM
//! always loads from the workspace VFS (or uses the empty-root fallback).

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::{Arc, OnceLock};

use serde::de::DeserializeOwned;

use crate::error::{Error, Result};
use crate::fs::FileSystem;

mod locate;
mod schema;

pub use schema::{ChromeSettings, OutputNames, PrintSettings};

use locate::find_conf_file;
use schema::{GameFile, GamesRootFile, RootFile};

use locate::CONF_FILE_NAME;

static CONF: OnceLock<Arc<Conf>> = OnceLock::new();

/// Fully resolved workspace: repo root, games, and Chrome search rules.
#[derive(Debug)]
pub struct Conf {
    /// Directory that contains the root `conf.json5` (empty in the VFS fallback).
    pub root: PathBuf,
    /// Directory that contains per-game folders.
    pub games_root: PathBuf,
    /// Game id used when a query omits the `{game}.` prefix.
    pub default_game: String,
    /// Native Chrome search rules (ignored in wasm).
    pub chrome: ChromeSettings,
    /// Game id → resolved folders and output names.
    pub games: HashMap<String, GamePaths>,
}

/// Absolute folders and print/output settings for one game.
#[derive(Debug, Clone)]
pub struct GamePaths {
    /// Game id (`game-name` in that game's conf).
    pub id: String,
    /// Game folder (sibling of `decks/`, `views/`, …).
    pub root: PathBuf,
    /// Deck `data.json5` trees.
    pub decks: PathBuf,
    /// Jinja / SCSS views.
    pub views: PathBuf,
    /// Named vars JSON5 files.
    pub vars: PathBuf,
    /// Game rules (not consumed by HTML render).
    pub rules: PathBuf,
    /// Generated HTML / PDF output.
    pub autogenerated: PathBuf,
    /// Duplex PDF output folder.
    pub duplex: PathBuf,
    /// Artifact filenames.
    pub output: OutputNames,
    /// Native print sheet geometry.
    pub print: PrintSettings,
}

/// Inject a conf (wasm / tests). Ignored if one is already loaded.
pub fn set_conf(conf: Conf) -> Arc<Conf> {
    CONF.get_or_init(|| Arc::new(conf)).clone()
}

/// Process-wide conf: cached native discovery, or an error in wasm.
pub fn conf() -> Result<Arc<Conf>> {
    if let Some(existing) = CONF.get() {
        return Ok(existing.clone());
    }
    #[cfg(target_arch = "wasm32")]
    {
        Err(Error::msg(
            "Native conf discovery is not available in wasm; use prepare_html with a FileSystem",
        ))
    }
    #[cfg(not(target_arch = "wasm32"))]
    {
        let loaded = Arc::new(load(&crate::fs::OsFs)?);
        Ok(CONF.get_or_init(|| loaded).clone())
    }
}

/// Build a [`Conf`] from `fs`: root file if found, otherwise the VFS fallback.
pub fn load<F>(fs: &F) -> Result<Conf>
where
    F: FileSystem + ?Sized,
{
    match find_conf_file(fs) {
        Ok(path) => build_conf(fs, path),
        Err(err) => {
            let virtual_root = fs.search_roots().iter().any(|root| root.as_os_str().is_empty());
            if virtual_root || fs.is_dir(Path::new("games")) {
                load_workspace_fallback(fs)
            } else {
                Err(err)
            }
        }
    }
}

impl Conf {
    /// Look up a game by id, or the default game when `id` is `None`.
    pub fn game(&self, id: Option<&str>) -> Result<&GamePaths> {
        let key = id.unwrap_or(self.default_game.as_str());
        self.games.get(key).ok_or_else(|| {
            let known = self.games.keys().cloned().collect::<Vec<_>>().join(", ");
            Error::msg(format!("Unknown game {key:?}. Known: {known}"))
        })
    }

    /// Game whose id is the first dotted segment of a deck name.
    pub fn game_for_deck_name(&self, name: &str) -> Result<&GamePaths> {
        let id = name.split('.').next().unwrap_or("");
        self.game(Some(id))
    }
}

/// `_autogenerated/` subfolder for a dotted deck name (`game.a.b` → `…/a/b`).
pub fn output_dir_for_name(loaded: &Conf, name: &str) -> Result<PathBuf> {
    let game = loaded.game_for_deck_name(name)?;
    let prefix = format!("{}.", game.id);
    let rest = name.strip_prefix(&prefix).ok_or_else(|| {
        Error::msg(format!("Deck name {name:?} must start with '{}.'", game.id))
    })?;
    let mut path = game.autogenerated.clone();
    for part in rest.split('.').filter(|part| !part.is_empty()) {
        path.push(part);
    }
    Ok(path)
}

/// Jinja search directory `views/` for the game that owns `name`.
pub fn views_for_deck_name(loaded: &Conf, name: &str) -> Result<PathBuf> {
    Ok(loaded.game_for_deck_name(name)?.views.clone())
}

fn load_workspace_fallback<F>(fs: &F) -> Result<Conf>
where
    F: FileSystem + ?Sized,
{
    let games_root = PathBuf::from("games");
    let games = if fs.is_dir(&games_root) {
        discover_games(fs, &games_root)?
    } else {
        HashMap::new()
    };
    let games_conf_path = games_root.join(CONF_FILE_NAME);
    let default_game = if fs.is_file(&games_conf_path) {
        let games_raw: GamesRootFile = parse_json5_file(fs, &games_conf_path)?;
        games_raw.default_game
    } else {
        games.keys().next().cloned().unwrap_or_default()
    };
    Ok(Conf {
        root: PathBuf::new(),
        games_root,
        default_game,
        chrome: ChromeSettings::default(),
        games,
    })
}

fn build_conf<F>(fs: &F, conf_path: PathBuf) -> Result<Conf>
where
    F: FileSystem + ?Sized,
{
    let raw: RootFile = parse_json5_file(fs, &conf_path)?;
    let root = conf_path
        .parent()
        .ok_or_else(|| Error::file(&conf_path, "has no parent directory"))?
        .to_path_buf();
    let games_root = root.join(&raw.games_root);
    let games_conf_path = games_root.join(CONF_FILE_NAME);
    let games_raw: GamesRootFile = parse_json5_file(fs, &games_conf_path)?;
    let games = discover_games(fs, &games_root)?;
    if games.is_empty() {
        return Err(Error::file(
            &games_root,
            "must contain at least one game folder with conf.json5",
        ));
    }
    if !games.contains_key(&games_raw.default_game) {
        return Err(Error::file(
            &games_conf_path,
            format!(
                "default_game {:?} is not a known game-name",
                games_raw.default_game
            ),
        ));
    }
    Ok(Conf {
        root,
        games_root,
        default_game: games_raw.default_game,
        chrome: raw.chrome,
        games,
    })
}

fn discover_games<F>(fs: &F, games_root: &Path) -> Result<HashMap<String, GamePaths>>
where
    F: FileSystem + ?Sized,
{
    if !fs.is_dir(games_root) {
        return Err(Error::file(games_root, "is not a directory"));
    }
    let mut games = HashMap::new();
    for path in fs.read_dir(games_root)? {
        if !fs.is_dir(&path) {
            continue;
        }
        let conf_path = path.join(CONF_FILE_NAME);
        if !fs.is_file(&conf_path) {
            continue;
        }
        let spec: GameFile = parse_json5_file(fs, &conf_path)?;
        let id = spec.game_name.clone();
        if games.contains_key(&id) {
            return Err(Error::file(
                &conf_path,
                format!("duplicate game-name {id:?}"),
            ));
        }
        games.insert(id.clone(), resolve_game(path, id, spec));
    }
    Ok(games)
}

fn resolve_game(game_root: PathBuf, id: String, spec: GameFile) -> GamePaths {
    let folders = spec.folders;
    GamePaths {
        id,
        decks: game_root.join(&folders.decks),
        views: game_root.join(&folders.views),
        vars: game_root.join(&folders.vars),
        rules: game_root.join(&folders.rules),
        autogenerated: game_root.join(&folders.autogenerated),
        duplex: game_root.join(&folders.duplex),
        root: game_root,
        output: spec.output,
        print: spec.print,
    }
}

fn parse_json5_file<F, T>(fs: &F, path: &Path) -> Result<T>
where
    F: FileSystem + ?Sized,
    T: DeserializeOwned,
{
    let text = fs.read_to_string(path)?;
    json5::from_str(&text).map_err(|err| Error::file(path, format!("invalid JSON5: {err}")))
}
