//! Serde shapes of the three `conf.json5` files.

use serde::Deserialize;

/// Repository-root `conf.json5`.
#[derive(Debug, Deserialize)]
pub struct RootFile {
    pub games_root: String,
    pub chrome: ChromeSettings,
}

/// `conf.json5` in the games folder.
#[derive(Debug, Deserialize)]
pub struct GamesRootFile {
    pub default_game: String,
}

/// `conf.json5` in a game folder.
#[derive(Debug, Deserialize)]
pub struct GameFile {
    #[serde(rename = "game-name")]
    pub game_name: String,
    pub folders: GameFolders,
    pub output: OutputNames,
    pub print: PrintSettings,
}

#[derive(Debug, Deserialize)]
pub struct GameFolders {
    pub decks: String,
    pub views: String,
    pub vars: String,
    pub rules: String,
    pub autogenerated: String,
    pub duplex: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct OutputNames {
    pub face_html: String,
    pub back_html: String,
    pub preview_html: String,
    pub face_pdf: String,
    pub back_pdf: String,
    pub duplex_pdf: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct PrintSettings {
    pub default_duplex: String,
    pub page_width_mm: f64,
    pub page_height_mm: f64,
    pub cols: i32,
    pub rows: i32,
    pub gap_x_mm: f64,
    pub gap_y_mm: f64,
    pub crop_mark_mm: f64,
    pub crop_mark_gap_mm: f64,
    pub crop_mark_thickness_pt: f64,
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct ChromeSettings {
    pub env_vars: Vec<String>,
    pub executables: Vec<String>,
    pub home_relative: Vec<String>,
}
