//! Serde shape of `conf.json5`. Every path-like field is required: there are
//! no hidden directory names in code.

use std::collections::HashMap;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct File {
    pub games_root: String,
    pub default_game: String,
    pub deck_data_files: Vec<String>,
    pub vars_file_extensions: Vec<String>,
    pub local_vars_dir: String,
    pub output: OutputNames,
    pub templates: TemplateNames,
    pub print: PrintSettings,
    pub chrome: ChromeSettings,
    pub games: HashMap<String, GameSpec>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct OutputNames {
    pub face_html: String,
    pub back_html: String,
    pub preview_html: String,
    pub manifest: String,
    pub face_pdf: String,
    pub back_pdf: String,
    pub duplex_pdf: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct TemplateNames {
    pub default_face: String,
    pub default_back: String,
    pub preview: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct PrintSettings {
    pub default_duplex: String,
    pub page_width_mm: f64,
    pub page_height_mm: f64,
    pub cols: i32,
    pub rows: i32,
    pub gap_x_mm: f64,
    pub gap_y_mm: f64,
    pub crop_mark_mm: f64,
    pub crop_mark_gap_mm: f64,
    pub crop_mark_thickness_pt: f64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct ChromeSettings {
    pub env_vars: Vec<String>,
    pub executables: Vec<String>,
    pub home_relative: Vec<String>,
}

#[derive(Debug, Deserialize)]
pub struct GameSpec {
    pub dir: String,
    pub decks: String,
    pub views: String,
    pub vars: String,
    pub rules: String,
    pub autogenerated: String,
    pub duplex: String,
}
