//! Serde shapes of the three `conf.json5` files.
//!
//! These types exist only to deserialize files. Runtime code uses [`super::Conf`]
//! and [`super::GamePaths`], which store resolved `PathBuf`s instead of the
//! relative folder names from disk.

use serde::Deserialize;

/// Repository-root `conf.json5`.
#[derive(Debug, Deserialize)]
pub struct RootFile {
    /// Directory that contains per-game folders, relative to this file.
    pub games_root: String,
    /// How the native CLI finds a Chrome/Chromium executable.
    pub chrome: ChromeSettings,
}

/// `conf.json5` in the games folder.
#[derive(Debug, Deserialize)]
pub struct GamesRootFile {
    /// Game id used when a deck query omits the `{game}.` prefix.
    pub default_game: String,
}

/// `conf.json5` in a game folder.
#[derive(Debug, Deserialize)]
pub struct GameFile {
    /// Stable game id; becomes the prefix of every deck name.
    #[serde(rename = "game-name")]
    pub game_name: String,
    /// Folder names under the game root.
    pub folders: GameFolders,
    /// Filenames written into `_autogenerated/`.
    pub output: OutputNames,
    /// A4 sheet layout used by the native PDF command.
    pub print: PrintSettings,
}

/// Relative folder names from a game `conf.json5`.
#[derive(Debug, Deserialize)]
pub struct GameFolders {
    /// Deck JSON5 trees.
    pub decks: String,
    /// Jinja / SCSS templates.
    pub views: String,
    /// Named vars files.
    pub vars: String,
    /// Rules documents.
    pub rules: String,
    /// Generated artifacts.
    pub autogenerated: String,
    /// Duplex PDF folder.
    pub duplex: String,
}

/// Output filenames for HTML and PDF artifacts.
#[derive(Debug, Clone, Deserialize)]
pub struct OutputNames {
    /// Face sheet HTML filename.
    pub face_html: String,
    /// Back sheet HTML filename.
    pub back_html: String,
    /// Preview page HTML filename.
    pub preview_html: String,
    /// Face PDF filename (CLI).
    pub face_pdf: String,
    /// Back PDF filename (CLI).
    pub back_pdf: String,
    /// Duplex sheet PDF filename (CLI).
    pub duplex_pdf: String,
}

/// Duplex sheet geometry, copied into `prepare_pdf_host::SheetLayout`.
#[derive(Debug, Clone, Deserialize)]
pub struct PrintSettings {
    /// Default duplex mode name (`long` / `short`).
    pub default_duplex: String,
    /// Sheet width in millimetres.
    pub page_width_mm: f64,
    /// Sheet height in millimetres.
    pub page_height_mm: f64,
    /// Cards per row.
    pub cols: i32,
    /// Cards per column.
    pub rows: i32,
    /// Horizontal gap between cards (mm).
    pub gap_x_mm: f64,
    /// Vertical gap between cards (mm).
    pub gap_y_mm: f64,
    /// Crop-mark length (mm).
    pub crop_mark_mm: f64,
    /// Gap from card edge to crop mark (mm).
    pub crop_mark_gap_mm: f64,
    /// Crop-mark stroke (pt).
    pub crop_mark_thickness_pt: f64,
}

/// Search rules for a local Chrome/Chromium binary.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct ChromeSettings {
    /// Environment variables that may hold an executable path.
    pub env_vars: Vec<String>,
    /// Absolute or conf-root-relative executable paths.
    pub executables: Vec<String>,
    /// Paths relative to the user home directory.
    pub home_relative: Vec<String>,
}
