//! [`deck_gen::FileSystem`] over the in-memory workspace [`Vfs`].
//!
//! HTML generation mutates the tree (writes `_autogenerated/…`). The adapter
//! holds [`Vfs`] in a `Mutex` so the MiniJinja `'static` loader can share it.
//! After `prepare_html`, the UI unwraps the `Arc` and takes the VFS back.

use std::path::{Component, Path, PathBuf};
use std::sync::Mutex;

use deck_gen::fs::FileSystem;
use deck_gen::{Error, Result};

use super::{join_path, Vfs};

/// [`FileSystem`] adapter: interior-mutable [`Vfs`] for the HTML pipeline.
pub struct VfsFs {
    vfs: Mutex<Vfs>,
}

impl VfsFs {
    /// Wrap an existing workspace tree.
    pub fn new(vfs: Vfs) -> Self {
        Self {
            vfs: Mutex::new(vfs),
        }
    }

    /// Recover the tree after `Arc::try_unwrap`.
    pub fn into_vfs(self) -> Vfs {
        self.vfs.into_inner().unwrap_or_else(|err| err.into_inner())
    }

    /// Snapshot the tree when the `Arc` is still shared.
    pub fn clone_vfs(&self) -> Vfs {
        self.lock().clone()
    }
}

impl FileSystem for VfsFs {
    fn read_to_string(&self, path: &Path) -> Result<String> {
        let key = vfs_key(path);
        self.lock()
            .read_file(&key)
            .map(str::to_string)
            .ok_or_else(|| Error::file(path, "not found"))
    }

    fn write(&self, path: &Path, contents: &str) -> Result<()> {
        let key = vfs_key(path);
        self.lock()
            .put_file(&key, contents.to_string())
            .map_err(|err| Error::file(path, err))
    }

    fn write_bytes(&self, path: &Path, contents: &[u8]) -> Result<()> {
        let key = vfs_key(path);
        self.lock()
            .put_bytes(&key, contents.to_vec())
            .map_err(|err| Error::file(path, err))
    }

    fn read_bytes(&self, path: &Path) -> Result<Vec<u8>> {
        let key = vfs_key(path);
        self.lock()
            .read_bytes(&key)
            .map(Vec::from)
            .ok_or_else(|| Error::file(path, "not found"))
    }

    fn create_dir_all(&self, path: &Path) -> Result<()> {
        let key = vfs_key(path);
        if key.is_empty() {
            return Ok(());
        }
        self.lock()
            .mkdir(&key)
            .map_err(|err| Error::file(path, err))
    }

    fn is_file(&self, path: &Path) -> bool {
        self.lock().is_file(&vfs_key(path))
    }

    fn is_dir(&self, path: &Path) -> bool {
        self.lock().is_dir(&vfs_key(path))
    }

    fn read_dir(&self, path: &Path) -> Result<Vec<PathBuf>> {
        let key = vfs_key(path);
        Ok(self
            .lock()
            .children(&key)
            .into_iter()
            .map(|(name, _)| PathBuf::from(join_path(&key, &name)))
            .collect())
    }

    fn canonicalize(&self, path: &Path) -> Result<PathBuf> {
        Ok(PathBuf::from(vfs_key(path)))
    }

    fn search_roots(&self) -> Vec<PathBuf> {
        vec![PathBuf::new()]
    }
}

impl VfsFs {
    fn lock(&self) -> std::sync::MutexGuard<'_, Vfs> {
        self.vfs.lock().unwrap_or_else(|err| err.into_inner())
    }
}

fn vfs_key(path: &Path) -> String {
    path.components()
        .filter_map(|component| match component {
            Component::Normal(part) => part.to_str(),
            _ => None,
        })
        .collect::<Vec<_>>()
        .join("/")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;
    use std::sync::Arc;

    use crate::fs::Vfs;

    #[test]
    fn empty_workspace_errors() {
        let fs: Arc<dyn FileSystem> = Arc::new(VfsFs::new(Vfs::default()));
        let err = deck_gen::prepare_html(fs).unwrap_err();
        assert!(
            err.to_string().contains("No deck data files"),
            "{err}"
        );
    }

    #[test]
    fn prepares_new_game_html() {
        let mut vfs = Vfs::default();
        let src = Path::new(env!("CARGO_MANIFEST_DIR")).join("../games/new-game");
        load_tree(&mut vfs, &src, "games/new-game");
        let fs = Arc::new(VfsFs::new(vfs));
        let n = deck_gen::prepare_html(fs.clone()).unwrap();
        assert_eq!(n, 2);
        let vfs = match Arc::try_unwrap(fs) {
            Ok(inner) => inner.into_vfs(),
            Err(arc) => arc.clone_vfs(),
        };
        let preview = vfs
            .read_file("games/new-game/_autogenerated/deck-1st/preview.html")
            .unwrap();
        assert!(preview.contains("First deck"), "{preview}");
        let face = vfs
            .read_file("games/new-game/_autogenerated/deck-1st/face.html")
            .unwrap();
        assert!(face.contains("Literal card"), "{face}");
        let back = vfs
            .read_file("games/new-game/_autogenerated/deck-2nd/back.html")
            .unwrap();
        assert!(back.contains("Second deck"), "{back}");
    }

    fn load_tree(vfs: &mut Vfs, src: &Path, dest: &str) {
        for entry in std::fs::read_dir(src).unwrap() {
            let entry = entry.unwrap();
            let name = entry.file_name().to_string_lossy().into_owned();
            if name == "_autogenerated" {
                continue;
            }
            let dest_path = join_path(dest, &name);
            if entry.file_type().unwrap().is_dir() {
                load_tree(vfs, &entry.path(), &dest_path);
            } else if !name.ends_with(".pdf") && !name.ends_with(".drawio") {
                let content = std::fs::read_to_string(entry.path()).unwrap();
                vfs.put_file(&dest_path, content).unwrap();
            }
        }
    }
}
