//! Generate face/back/preview HTML for every deck in the workspace VFS.

use std::collections::HashMap;
use std::sync::Arc;

use minijinja::value::Value as JinjaValue;
use minijinja::{context, AutoEscape, Environment};
use serde::Deserialize;
use serde_json::{Map, Value};

use deck_gen::card::{card_from_row, normalize_map};
use deck_gen::conf::OutputNames;
use deck_gen::subst::{
    expand_sticky_spans, extract_json_object_for_key, lookup_var, substitute_placeholders, Resolve,
};

use crate::fs::{file_name, join_path, parent_path, Vfs};

#[derive(Clone, Deserialize)]
struct GameConf {
    #[serde(rename = "game-name")]
    game_name: String,
    folders: GameFolders,
    output: OutputNames,
}

#[derive(Clone, Deserialize)]
struct GameFolders {
    decks: String,
    views: String,
    vars: String,
    autogenerated: String,
}

#[derive(Clone)]
struct GameInfo {
    id: String,
    views: String,
    vars: String,
    autogenerated: String,
    output: OutputNames,
}

struct DeckJob {
    game: GameInfo,
    data_path: String,
    expected_name: String,
}

pub fn prepare_all_html(vfs: &mut Vfs) -> Result<usize, String> {
    let jobs = collect_jobs(vfs)?;
    if jobs.is_empty() {
        return Err("No deck data files found under configured games".into());
    }
    for job in &jobs {
        prepare_one(vfs, job)?;
    }
    Ok(jobs.len())
}

fn collect_jobs(vfs: &Vfs) -> Result<Vec<DeckJob>, String> {
    let mut games = Vec::new();
    for (name, is_dir) in vfs.children("games") {
        if !is_dir {
            continue;
        }
        let root = join_path("games", &name);
        let conf_path = join_path(&root, "conf.json5");
        let Some(text) = vfs.read_file(&conf_path) else {
            continue;
        };
        let spec: GameConf = json5::from_str(text)
            .map_err(|err| format!("{conf_path}: invalid JSON5: {err}"))?;
        let decks = join_path(&root, &spec.folders.decks);
        games.push((
            decks,
            GameInfo {
                id: spec.game_name,
                views: join_path(&root, &spec.folders.views),
                vars: join_path(&root, &spec.folders.vars),
                autogenerated: join_path(&root, &spec.folders.autogenerated),
                output: spec.output,
            },
        ));
    }

    let mut jobs = Vec::new();
    let (_, files) = vfs.files_and_dirs();
    for (path, _) in files {
        if file_name(&path) != "data.json5" {
            continue;
        }
        let Some((decks, game)) = games.iter().find(|(decks, _)| {
            path == *decks || path.starts_with(&format!("{decks}/"))
        }) else {
            continue;
        };
        let parent = parent_path(&path);
        let prefix = format!("{decks}/");
        let rest = parent
            .strip_prefix(&prefix)
            .unwrap_or("")
            .split('/')
            .filter(|part| !part.is_empty())
            .collect::<Vec<_>>()
            .join(".");
        let expected_name = format!("{}.{}", game.id, rest);
        jobs.push(DeckJob {
            game: game.clone(),
            data_path: path,
            expected_name,
        });
    }
    Ok(jobs)
}

fn prepare_one(vfs: &mut Vfs, job: &DeckJob) -> Result<(), String> {
    let directory = parent_path(&job.data_path);
    let payload = load_payload(vfs, &job.data_path, &job.game.vars)?;
    let (name, fields, cards) = deck_from_payload(&job.data_path, payload)?;
    if name != job.expected_name {
        return Err(format!(
            "{path}: name {name:?} must match relative path {expected:?}",
            path = job.data_path,
            expected = job.expected_name
        ));
    }

    let face_template = template_for(&fields, &job.data_path, "face")?;
    let back_template = template_for(&fields, &job.data_path, "back")?;
    let width = number_field(&fields, "card_width_mm")?;
    let height = number_field(&fields, "card_height_mm")?;
    let game_name = fields
        .get("game_name")
        .and_then(Value::as_str)
        .unwrap_or("")
        .to_string();

    let env = jinja_env(
        vfs.clone(),
        directory,
        job.game.views.clone(),
        game_name.clone(),
        width,
        height,
    )?;
    let ctx = template_context(&fields, &cards, &game_name, width, height);

    let out = output_dir(&job.game.autogenerated, &job.game.id, &name)?;
    let face_html = env
        .get_template(&face_template)
        .and_then(|t| t.render(&ctx))
        .map_err(|err| err.to_string())?;
    let back_html = env
        .get_template(&back_template)
        .and_then(|t| t.render(&ctx))
        .map_err(|err| err.to_string())?;
    let preview_html = env
        .get_template(&job.game.output.preview_html)
        .and_then(|t| t.render(&ctx))
        .map_err(|err| err.to_string())?;

    vfs.put_file(&join_path(&out, &job.game.output.face_html), face_html)?;
    vfs.put_file(&join_path(&out, &job.game.output.back_html), back_html)?;
    vfs.put_file(
        &join_path(&out, &job.game.output.preview_html),
        preview_html,
    )?;
    Ok(())
}

fn load_payload(vfs: &Vfs, data_path: &str, vars_dir: &str) -> Result<Map<String, Value>, String> {
    let raw = vfs
        .read_file(data_path)
        .ok_or_else(|| format!("{data_path}: Deck data file does not exist"))?;
    let mut file_cache: HashMap<String, Value> = HashMap::new();
    let pass1 = expand_file_refs(vfs, vars_dir, raw, &mut file_cache)?;
    let local_vars =
        extract_json_object_for_key(&pass1, "vars").map_err(|err| err.to_string())?;
    let local_vars = local_vars.unwrap_or_else(|| Value::Object(Map::new()));
    let pass2 = expand_all_refs(vfs, vars_dir, &pass1, &mut file_cache, &local_vars)?;
    let expanded = expand_sticky_spans(&pass2).map_err(|err| err.to_string())?;
    let payload: Value =
        json5::from_str(&expanded).map_err(|err| format!("{data_path}: is not valid JSON5: {err}"))?;
    match payload {
        Value::Object(map) => Ok(map),
        _ => Err(format!("{data_path}: must be a JSON object")),
    }
}

fn expand_file_refs(
    vfs: &Vfs,
    vars_dir: &str,
    raw: &str,
    file_cache: &mut HashMap<String, Value>,
) -> Result<String, String> {
    substitute_placeholders(raw, |placeholder| {
        if !placeholder.contains(':') {
            return Ok(Resolve::Keep);
        }
        let (file_stem, path) = split_file_ref(placeholder)?;
        let tree = load_named_vars(vfs, vars_dir, file_cache, file_stem)?;
        Ok(Resolve::Value(lookup_var(&tree, path)?.clone()))
    })
    .map_err(|err| err.to_string())
}

fn expand_all_refs(
    vfs: &Vfs,
    vars_dir: &str,
    raw: &str,
    file_cache: &mut HashMap<String, Value>,
    local_vars: &Value,
) -> Result<String, String> {
    substitute_placeholders(raw, |placeholder| {
        if placeholder.contains(':') {
            let (file_stem, path) = split_file_ref(placeholder)?;
            let tree = load_named_vars(vfs, vars_dir, file_cache, file_stem)?;
            return Ok(Resolve::Value(lookup_var(&tree, path)?.clone()));
        }
        let mut root = Map::new();
        root.insert("vars".into(), local_vars.clone());
        Ok(Resolve::Value(
            lookup_var(&Value::Object(root), placeholder)?.clone(),
        ))
    })
    .map_err(|err| err.to_string())
}

fn load_named_vars(
    vfs: &Vfs,
    vars_dir: &str,
    cache: &mut HashMap<String, Value>,
    name: &str,
) -> deck_gen::Result<Value> {
    if let Some(existing) = cache.get(name) {
        return Ok(existing.clone());
    }
    if !is_vars_stem(name) {
        return Err(deck_gen::Error::msg(format!(
            "Invalid vars file name {name:?}"
        )));
    }
    let path = join_path(vars_dir, &format!("{name}.json5"));
    let text = vfs.read_file(&path).ok_or_else(|| {
        deck_gen::Error::msg(format!("Vars file '{name}' not found in: {path}"))
    })?;
    let loaded: Value = json5::from_str(text).map_err(|err| {
        deck_gen::Error::file(path.clone(), format!("is not valid JSON5: {err}"))
    })?;
    cache.insert(name.to_string(), loaded.clone());
    Ok(loaded)
}

fn split_file_ref(placeholder: &str) -> deck_gen::Result<(&str, &str)> {
    let (name, path) = placeholder.split_once(':').ok_or_else(|| {
        deck_gen::Error::msg(format!(
            "Expected file:path in placeholder {placeholder:?}"
        ))
    })?;
    Ok((name.trim(), path.trim()))
}

fn is_vars_stem(name: &str) -> bool {
    !name.is_empty() && name != "." && name != ".." && !name.contains('/') && !name.contains('\\')
}

fn deck_from_payload(
    path: &str,
    payload: Map<String, Value>,
) -> Result<(String, Map<String, Value>, Vec<Value>), String> {
    let deck_fields = payload
        .get("deck")
        .and_then(Value::as_object)
        .cloned()
        .ok_or_else(|| format!("{path}: must contain object 'deck'"))?;
    let card_rows = payload
        .get("cards")
        .and_then(Value::as_array)
        .cloned()
        .ok_or_else(|| format!("{path}: must contain list 'cards'"))?;
    let extras: Map<String, Value> = payload
        .iter()
        .filter(|(key, _)| *key != "deck" && *key != "cards")
        .map(|(key, value)| (key.clone(), value.clone()))
        .collect();

    let mut data = normalize_map(&deck_fields);
    let extra_fields = normalize_map(&extras);
    for (key, value) in &extra_fields {
        data.insert(key.clone(), value.clone());
    }
    let name = extra_fields
        .get("name")
        .and_then(Value::as_str)
        .filter(|name| !name.is_empty())
        .ok_or_else(|| format!("{path}: must contain 'name'"))?
        .to_string();
    if !data.contains_key("view") {
        return Err(format!("{path}: must contain 'view'"));
    }
    data.insert("key".into(), Value::String(name.clone()));

    let defaults: Map<String, Value> = data
        .iter()
        .filter(|(key, _)| key.starts_with("card_"))
        .map(|(key, value)| (key.clone(), value.clone()))
        .collect();
    let cards = card_rows
        .iter()
        .enumerate()
        .map(|(index, row)| card_from_row(index + 1, row, &defaults))
        .collect();
    Ok((name, data, cards))
}

fn template_for(fields: &Map<String, Value>, path: &str, side: &str) -> Result<String, String> {
    fields
        .get("view")
        .and_then(Value::as_object)
        .and_then(|view| view.get(side))
        .and_then(Value::as_str)
        .filter(|name| !name.is_empty())
        .map(str::to_string)
        .ok_or_else(|| format!("{path}: view.{side} is required"))
}

fn number_field(fields: &Map<String, Value>, key: &str) -> Result<f64, String> {
    let value = fields
        .get(key)
        .ok_or_else(|| format!("missing {key}"))?;
    Ok(match value {
        Value::Number(n) => n.as_f64().unwrap_or(0.0),
        Value::String(text) => text.parse().unwrap_or(0.0),
        _ => 0.0,
    })
}

fn output_dir(autogenerated: &str, game_id: &str, name: &str) -> Result<String, String> {
    let prefix = format!("{game_id}.");
    let rest = name.strip_prefix(&prefix).ok_or_else(|| {
        format!("Deck name {name:?} must start with '{prefix}'")
    })?;
    let mut path = autogenerated.to_string();
    for part in rest.split('.').filter(|part| !part.is_empty()) {
        path = join_path(&path, part);
    }
    Ok(path)
}

fn template_context(
    fields: &Map<String, Value>,
    cards: &[Value],
    game_name: &str,
    width: f64,
    height: f64,
) -> minijinja::value::Value {
    let deck_obj = JinjaValue::from_serialize(fields);
    let cards_obj = JinjaValue::from_serialize(cards);
    context! {
        deck => deck_obj,
        cards => cards_obj,
        game_name => game_name,
        card_width_mm => width,
        card_height_mm => height,
    }
}

fn jinja_env(
    vfs: Vfs,
    deck_dir: String,
    views: String,
    game_name: String,
    width: f64,
    height: f64,
) -> Result<Environment<'static>, String> {
    let search = Arc::new(vec![deck_dir, views]);
    let mut raw_env = Environment::new();
    configure_env(&mut raw_env, &game_name, width, height);
    attach_loader(&mut raw_env, vfs.clone(), search.clone(), None);

    let mut env = Environment::new();
    configure_env(&mut env, &game_name, width, height);
    attach_loader(&mut env, vfs, search, Some(Arc::new(raw_env)));
    Ok(env)
}

fn configure_env(env: &mut Environment<'static>, game_name: &str, width: f64, height: f64) {
    env.set_trim_blocks(true);
    env.set_lstrip_blocks(true);
    env.set_auto_escape_callback(|name| {
        if name.ends_with(".html") || name.ends_with(".xml") {
            AutoEscape::Html
        } else {
            AutoEscape::None
        }
    });
    env.add_global("game_name", game_name.to_string());
    env.add_global("card_width_mm", width);
    env.add_global("card_height_mm", height);
}

fn attach_loader(
    env: &mut Environment<'static>,
    vfs: Vfs,
    search: Arc<Vec<String>>,
    scss_env: Option<Arc<Environment<'static>>>,
) {
    env.set_loader(move |name| {
        let Some(raw) = read_template(name, &vfs, &search) else {
            return Ok(None);
        };
        if let Some(scss_env) = &scss_env {
            if name.ends_with(".scss") {
                let rendered = scss_env.render_str(&raw, context! {})?;
                let css = grass::from_string(rendered, &grass::Options::default()).map_err(|err| {
                    minijinja::Error::new(minijinja::ErrorKind::InvalidOperation, err.to_string())
                })?;
                return Ok(Some(css));
            }
        }
        Ok(Some(raw))
    });
}

fn read_template(name: &str, vfs: &Vfs, search: &[String]) -> Option<String> {
    for dir in search {
        let path = join_path(dir, name);
        if let Some(content) = vfs.read_file(&path) {
            return Some(content.to_string());
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn empty_workspace_errors() {
        let mut vfs = Vfs::default();
        let err = prepare_all_html(&mut vfs).unwrap_err();
        assert!(err.contains("No deck data files"), "{err}");
    }

    #[test]
    fn prepares_new_game_html() {
        let mut vfs = Vfs::default();
        let src = Path::new(env!("CARGO_MANIFEST_DIR")).join("../games/new-game");
        load_tree(&mut vfs, &src, "games/new-game");
        let n = prepare_all_html(&mut vfs).unwrap();
        assert_eq!(n, 2);
        let preview = vfs
            .read_file("games/new-game/_autogenerated/deck-1st/preview.html")
            .unwrap();
        assert!(preview.contains("First deck"), "{preview}");
        let face = vfs
            .read_file("games/new-game/_autogenerated/deck-1st/face.html")
            .unwrap();
        assert!(face.contains("Literal card"), "{face}");
        let back = vfs
            .read_file("games/new-game/_autogenerated/deck-2nd/back.html")
            .unwrap();
        assert!(back.contains("Second deck"), "{back}");
    }

    fn load_tree(vfs: &mut Vfs, src: &Path, dest: &str) {
        for entry in std::fs::read_dir(src).unwrap() {
            let entry = entry.unwrap();
            let name = entry.file_name().to_string_lossy().into_owned();
            if name == "_autogenerated" {
                continue;
            }
            let dest_path = join_path(dest, &name);
            if entry.file_type().unwrap().is_dir() {
                load_tree(vfs, &entry.path(), &dest_path);
            } else if !name.ends_with(".pdf") && !name.ends_with(".drawio") {
                let content = std::fs::read_to_string(entry.path()).unwrap();
                vfs.put_file(&dest_path, content).unwrap();
            }
        }
    }
}
