//! AI orchestration: install defaults, list models, edit-target predicate, run_loop.

use leptos::prelude::*;
use wasm_bindgen_futures::spawn_local;

use deck_gen_wasm_ai::{install_ai_defaults, needs_ai_install, AiEngine, AiRequest};
use deck_gen_wasm_fs::{path_is_or_under, Vfs};
use deck_gen_wasm_locale as locale;
use deck_gen_wasm_locale::keys;
use deck_gen_wasm_template::{game_roots_from_paths, install_game_help, needs_game_help};
use progress_viewer::progress_wrapper;

use super::{OpenTab, TabKind, Workspace};

/// JSON5 files under `ai-models/` as `(path, label)`.
pub fn list_ai_models(vfs: &Vfs) -> Vec<(String, String)> {
    deck_gen_wasm_ai::list_model_files(vfs)
}

/// Active for a **file** that lives in a game tree and is not under `_autogenerated`.
pub fn ai_edit_target(vfs: &Vfs, file: Option<&str>) -> Option<(String, String)> {
    let file = file?;
    if !vfs.is_file(file) {
        return None;
    }
    if deck_gen_wasm_ai::is_autogenerated_path(file) {
        return None;
    }
    let mut paths = Vec::new();
    vfs.visit_entries(|path, _| paths.push(path.to_string()));
    let root = game_roots_from_paths(paths)
        .into_iter()
        .filter(|root| !root.is_empty())
        .find(|root| path_is_or_under(file, root))?;
    Some((root, file.to_string()))
}

impl Workspace {
    /// Copy bundled game-help and default AI model files if missing / HTML-shell.
    pub fn ensure_ai_files(&self) {
        let result = self.vfs.try_update(|vfs| {
            if needs_game_help(vfs) {
                install_game_help(vfs)?;
            }
            if needs_ai_install(vfs) {
                install_ai_defaults(vfs)?;
            }
            Ok(())
        });
        match result {
            Some(Err(err)) => self.status.set(err),
            None => self.status.set(locale::localize(keys::STATUS_COULD_NOT_UPDATE)),
            Some(Ok(())) => {}
        }
    }

    /// `(game_root, file)` when the AI-edit button should be enabled.
    pub fn current_ai_edit_target(&self) -> Option<(String, String)> {
        let file = match self.active_tab.get() {
            Some(tab) if tab.kind == TabKind::Edit => Some(tab.path),
            _ => self
                .selected
                .get()
                .filter(|path| self.vfs.with(|vfs| vfs.is_file(path))),
        };
        self.vfs.with(|vfs| ai_edit_target(vfs, file.as_deref()))
    }

    /// One prompt → agent loop. Updates VFS after each round so the log preview lives.
    pub fn run_ai(
        &self,
        req: AiRequest,
        model_path: &str,
        warning: RwSignal<Option<String>>,
    ) {
        if !self.try_begin_async(locale::localize(keys::STATUS_AI_RUNNING)) {
            return;
        }
        let workspace = *self;
        let model_path = model_path.to_string();
        spawn_local(async move {
            let progress = workspace.progress_handle();
            progress_wrapper!(progress, {
                workspace.flush_draft();
                let mut vfs = workspace.vfs.get_untracked();
                let engine = match AiEngine::from_conf(&vfs, &model_path) {
                    Ok(engine) => engine,
                    Err(err) => {
                        warning.set(Some(err));
                        workspace.status.set(String::new());
                        workspace.finish_async();
                        return;
                    }
                };
                progress.set(8.0);
                let mut opened = false;
                let mut round = 0u32;
                let result = engine
                    .run_loop(req, &mut vfs, |vfs, log_path| {
                        round += 1;
                        progress.set((8.0 + round as f32 * 6.0).min(92.0));
                        workspace.vfs.set(vfs.clone());
                        if !opened {
                            opened = true;
                            workspace.expand_ancestors(log_path);
                            workspace.open_tab(OpenTab {
                                path: log_path.to_string(),
                                kind: TabKind::Preview,
                            });
                        }
                    })
                    .await;
                workspace.vfs.set(vfs);
                match result {
                    Ok(()) => {
                        workspace
                            .status
                            .set(locale::localize(keys::STATUS_AI_DONE));
                    }
                    Err(err) => {
                        warning.set(Some(err));
                        workspace.status.set(String::new());
                    }
                }
            });
            workspace.finish_async();
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn vfs_with_game() -> Vfs {
        let mut vfs = Vfs::default();
        vfs.put_file("games/a/game.json5", "{}".into()).unwrap();
        vfs.put_file("games/a/decks/d/data.json5", "x".into())
            .unwrap();
        vfs.put_file("games/a/_autogenerated/preview.html", "p".into())
            .unwrap();
        vfs.put_file("user-help.md", "# h".into()).unwrap();
        vfs.mkdir("games/a/views").unwrap();
        vfs
    }

    #[test]
    fn ai_edit_active_on_game_source_file() {
        let vfs = vfs_with_game();
        let hit = ai_edit_target(&vfs, Some("games/a/decks/d/data.json5"));
        assert_eq!(
            hit,
            Some(("games/a".into(), "games/a/decks/d/data.json5".into()))
        );
    }

    #[test]
    fn ai_edit_inactive_on_autogen() {
        let vfs = vfs_with_game();
        assert_eq!(
            ai_edit_target(&vfs, Some("games/a/_autogenerated/preview.html")),
            None
        );
    }

    #[test]
    fn ai_edit_inactive_outside_game() {
        let vfs = vfs_with_game();
        assert_eq!(ai_edit_target(&vfs, Some("user-help.md")), None);
    }

    #[test]
    fn ai_edit_inactive_on_game_folder() {
        let vfs = vfs_with_game();
        assert_eq!(ai_edit_target(&vfs, Some("games/a")), None);
        assert_eq!(ai_edit_target(&vfs, Some("games/a/views")), None);
    }
}
